const {defaults,calculate,specs,validate}=Afterheat;
let state={...defaults},paused=false;
const $=id=>document.getElementById(id),fmt=(n,d=1)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const compact=n=>!Number.isFinite(n)?'—':Math.abs(n)>=10000?n.toExponential(2):fmt(n);
function updateInputError(){const invalid=specs.filter(([key])=>$(key+'-value').getAttribute('aria-invalid')==='true');$('input-error').hidden=!invalid.length;if(invalid.length)$('input-error').textContent='Correct '+invalid.map(s=>s[1]).join(', ')+'. Results use the last valid assumptions.';}
function changeInput(key,value){const spec=specs.find(s=>s[0]===key);if(!Number.isFinite(value)||value<spec[2]||value>spec[3]){$(key+'-value').setAttribute('aria-invalid','true');updateInputError();return;}$(key+'-value').removeAttribute('aria-invalid');state[key]=value;$('scenario').value='custom';$('scenario-note').textContent='Custom assumptions. Outputs recalculate automatically.';updateInputError();render();}
for(const [key,label,min,max,step,unit,group,sliderMin,sliderMax] of specs){const el=document.createElement('div');el.className='slider-control';el.innerHTML=`<label class="assumption-label" for="${key}-value">${label}</label><div class="editable-value"><input type="number" id="${key}-value" min="${min}" max="${max}" step="any" value="${state[key]}" inputmode="decimal"><span>${unit}</span></div><input type="range" id="${key}" min="${sliderMin}" max="${sliderMax}" step="any" value="${state[key]}" aria-label="${label} slider"><div class="range-endpoints"><span id="${key}-min"></span><span id="${key}-max"></span></div>`;$(group+'-controls').append(el);$(key+'-value').addEventListener('input',e=>changeInput(key,e.target.valueAsNumber));$(key).addEventListener('input',e=>{const value=Math.min(max,Math.max(min,Number((Math.round(Number(e.target.value)/step)*step).toFixed(6))));$(key+'-value').value=value;changeInput(key,value);});}
const presets={baseline:{...defaults},low:{...defaults,temp:150,heat:150,ratio:1.5},high:{...defaults,temp:600,heat:800,ratio:3}};
function setPreset(name){state={...presets[name]};for(const [key]of specs){$(key+'-value').removeAttribute('aria-invalid');$(key+'-value').value=state[key];}updateInputError();$('scenario').value=name;$('scenario-note').textContent=name==='high'?'Hypothetical heat quality; not a storage-system claim.':name==='low'?'Explore why low-grade heat can struggle to generate power.':'Illustrative assumptions, not measured waste data.';render()}
$('scenario').addEventListener('change',e=>{if(presets[e.target.value])setPreset(e.target.value)});$('reset').onclick=()=>{paused=false;updateMotion();setPreset('baseline')};
function updateMotion(){$('motion').setAttribute('aria-pressed',String(paused));$('motion').textContent=paused?'▷ Resume flow':'Ⅱ Pause flow';$('schematic').classList.toggle('paused',paused)}$('motion').onclick=()=>{paused=!paused;updateMotion()};
document.querySelector('a[href="#model"]').addEventListener('click',()=>{$('model').open=true});
function render(){for(const [key,label,min,max,step,unit,group,sliderMin,sliderMax] of specs){const lo=Math.min(sliderMin,state[key]),hi=Math.max(sliderMax,state[key]);$(key).min=lo;$(key).max=hi;$(key).value=state[key];$(key).style.setProperty('--fill',`${100*(state[key]-lo)/(hi-lo)}%`);if($(key+'-value').getAttribute('aria-invalid')!=='true'&&document.activeElement!==$(key+'-value'))$(key+'-value').value=state[key];$(key+'-min').textContent=fmt(lo,lo%1?3:0);$(key+'-max').textContent=fmt(hi,hi%1?3:0);}
$('live-assumptions').textContent=`Current values: compressor ${state.compressor}%; turbine ${state.turbine}%; generator/motor ${state.generator}%; auxiliaries ${state.auxiliary}% of captured heat; hot/cold approaches ${state.hotApproach}/${state.coldApproach} K; cₚ ${state.cp} kJ/(kg·K); γ ${state.gamma}; minimum heating margin ${state.margin} K.`;
$('gas-label').textContent=state.cp===defaults.cp&&state.gamma===defaults.gamma?'N₂ approximation · closed loop':'Custom ideal gas · closed loop';
const m=calculate(state);$('net').textContent=m.valid?fmt(m.net):'—';$('efficiency').textContent=m.valid?fmt(m.eff):'—';$('rejected').textContent=m.valid?fmt(m.rejected,0):'—';$('source-kw').textContent=compact(state.heat)+' kWth';$('diagram-power').textContent=m.valid?compact(m.net)+' kWe':'No solution';for(const [id,v]of[['t1',m.T1],['t2',m.T2],['t3',m.T3],['t4',m.T4]])$(id).textContent=fmt(v-273.15,0)+' °C';const positive=m.valid&&m.net>0;$('schematic').classList.toggle('invalid',!positive);$('status').classList.toggle('warning',!positive);$('status-symbol').textContent=positive?'✓':'!';$('status-title').textContent=positive?'Positive net output in this model':m.valid?'This scenario consumes net electricity':'No feasible cycle at these settings';$('status-message').textContent=positive?`Turbine: ${fmt(m.wt)} kW · Compressor: ${fmt(m.wc)} kW · Assumed gas flow: ${fmt(m.mass,2)} kg/s. Physical feasibility is unverified.`:m.valid?'Compressor demand and losses exceed useful generation. Try a hotter source, lower pressure ratio, or cooler sink.':({heat:'The heating margin is not met. Lower pressure ratio, raise source temperature, or review the temperature approaches.',cooling:'Turbine exhaust cannot reject heat to the assumed cooler outlet. Review pressure ratio and temperatures.',absolute:'An assumed gas temperature is at or below absolute zero. Review the source, sink and temperature approaches.',noheat:'There is no captured heat. Increase available heat or the captured fraction.'}[m.reason]);$('net-description').textContent=m.valid&&m.net<0?'Negative = external electricity required':'After compressor and auxiliary loads';drawCurve(m);drawBalance(m)}
function drawCurve(m){const svg=$('curve'),samples=[],rmin=1,rmax=Math.max(6,state.ratio);for(let i=0;i<=100;i++){const r=rmin+(rmax-rmin)*i/100;const p=calculate({...state,ratio:r});samples.push({r,p})}const finite=samples.filter(x=>x.p.valid);let lo=Math.min(0,...finite.map(x=>x.p.net)),hi=Math.max(1,...finite.map(x=>x.p.net));if(m.valid){lo=Math.min(lo,m.net);hi=Math.max(hi,m.net)}const pad=(hi-lo)*.12;lo-=pad;hi+=pad;const x=r=>50+(r-rmin)/(rmax-rmin)*490,y=v=>160-(v-lo)/(hi-lo)*145;let html='';for(let i=0;i<4;i++){let v=lo+(hi-lo)*i/3;html+=`<path d="M50 ${y(v)}H540" stroke="#e8edef"/><text x="40" y="${y(v)+4}" text-anchor="end" fill="#86939b" font-size="12">${Math.abs(v)>=10000?v.toExponential(1):fmt(v,0)}</text>`}html+=`<path d="M50 ${y(0)}H540" stroke="#b7c5bd" stroke-dasharray="4 4"/>`;for(const r of Array.from({length:5},(_,i)=>rmin+(rmax-rmin)*(i+1)/5))html+=`<text x="${x(r)}" y="188" text-anchor="middle" fill="#86939b" font-size="12">${fmt(r,1)}:1</text>`;let d='',last=false;for(const s of samples){if(s.p.valid){d+=`${last?'L':'M'}${x(s.r)},${y(s.p.net)} `;last=true}else last=false}html+=`<path d="${d}" stroke="#5c805f" stroke-width="3" fill="none"/>`;if(m.valid)html+=`<path d="M${x(state.ratio)} 8V162" stroke="#849784" stroke-dasharray="3 4"/><circle cx="${x(state.ratio)}" cy="${y(m.net)}" r="6" fill="#b9ef72" stroke="#365440" stroke-width="2"/>`;if(!finite.length)html+='<text x="285" y="85" text-anchor="middle" fill="#86939b" font-size="14">No feasible cycle in this range</text>';svg.innerHTML=html;svg.setAttribute('aria-label',`Net output versus pressure ratio from ${rmin} to ${rmax}. Current ratio ${state.ratio}; ${m.valid?fmt(m.net)+' kilowatts net':'no feasible solution'}. Negative values require external electricity.`)}
function drawBalance(m){$('total-source').textContent=fmt(state.heat,0)+' kW';if(!m.valid){$('balance-bar').setAttribute('aria-label','Energy balance unavailable');$('balance-bar').innerHTML='';$('balance-rows').innerHTML='<p class="hint">Energy balance unavailable. Adjust the operating conditions to obtain a feasible cycle.</p>';return}const rows=m.net>=0?[['Net electricity',m.net,'#a2c96f'],['Cycle cooling',m.cooler,'#7caebd'],['Uncaptured heat',m.uncaptured,'#cbd3d9'],['Conversion & auxiliaries',m.loss,'#ad9680']]:[['External electricity input',-m.net,'#d9a06c'],['Cycle cooling',m.cooler,'#7caebd'],['Uncaptured heat',m.uncaptured,'#cbd3d9'],['Conversion & auxiliaries',m.loss,'#ad9680']];const total=m.net>=0?state.heat:state.heat-m.net;const barRows=m.net>=0?rows:rows.slice(1);$('balance-bar').innerHTML=barRows.map(([n,v,c])=>`<span style="width:${100*v/total}%;background:${c}" title="${n}: ${fmt(v)} kW"></span>`).join('');$('balance-rows').innerHTML=rows.map(([n,v,c])=>`<div class="balance-row"><span><i class="key" style="background:${c}"></i>${n}</span><strong>${fmt(v)} kW</strong></div>`).join('');$('balance-bar').setAttribute('aria-label','Energy balance: '+rows.map(([n,v])=>n+' '+fmt(v)+' kilowatts').join(', '))}
window.getSimulation=()=>({conditions:{...state},engine:'brayton'});
render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const properties=Object.fromEntries(specs.map(([k,l,min,max])=>[k,{type:'number',description:l,minimum:min,maximum:max}]));try{Promise.resolve(document.modelContext.registerTool({name:'configure_turbine_simulation',title:'Configure decay-heat turbine simulation',description:'Update editable gas-turbine assumptions and return the calculated energy balance.',inputSchema:{type:'object',properties,additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');const next={...state};for(const [k,v]of Object.entries(input)){if(!specs.some(s=>s[0]===k))throw new Error('Unknown assumption: '+k);next[k]=v;}validate(next);state=next;for(const [key]of specs){$(key+'-value').removeAttribute('aria-invalid');$(key+'-value').value=state[key];}updateInputError();$('scenario').value='custom';$('scenario-note').textContent='Custom assumptions. Outputs recalculate automatically.';render();const m=calculate(state);return{conditions:{...state},feasible:m.valid,netElectricalKW:m.valid?m.net:null,efficiencyPercent:m.valid?m.eff:null};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}
